Profile stayls
Olyazarichna/appFriendsTrip pull request #12
Opened 2023-01-17 19:29 UTC by Vitaliy28031985

Стилізував  екран профілю.

2023-01-17 21:30 UTC, serg-rsv requested changes
Виправ, будь ласка, друкарські помилки в назвах компонентів і відповідно файлах.

2023-01-17 21:30 UTC, serg-rsv commented on components/Prolile/CameraProlileComponents.js
>  export default function CameraProlileComponents({
Camera**Prolile**Components треба перевірити назву компоненту і файлу

2023-01-17 21:30 UTC, serg-rsv commented on components/Prolile/GallertProlileComponents.js
>  export default function GallertProlileComponents({
Galle_rt_Pro_l_ileComponents - треба перевірити назви

2023-01-17 21:30 UTC, serg-rsv commented on screens/auth/RegistrationScreen.js
>               changeInput(value, setState, setPhoneChange, 'phone',  validation.phone, setCheckValidPhone)
Якось забагато аргументів для функції. Можливо зручніше зробити об'єкт налаштувань?

2023-01-18 14:38 UTC, Vitaliy28031985 commented on screens/auth/RegistrationScreen.js
>               changeInput(value, setState, setPhoneChange, 'phone',  validation.phone, setCheckValidPhone)
Створення Об'єкту налаштувань буде складно через те що як мінімум 2 аргументи є локальними ( 'phone', value). Тому поки нехай буде так. Ок?

2023-01-18 15:08 UTC, serg-rsv approved these changes

2023-01-18 15:08 UTC, merged